package ClassWork.Lessons_20_per_29.L_27_Exceptions_Errors_2;

public class test_3 {
    public static void main(String[] args) throws Exception{
        Exception exception = null;
        throw exception;
    }
}
